- hosts: all
  become: true  #permet de devenir super utilisateur
  tasks:
  - name: avoir une vache qui parle
    apt: name="cowsay" state="latest"  

  - name: avoir un serveur Apache2 installé 
    apt: name="apache2" state="present"

  - name: avoir un demon Apache2 qui tourne
    service: name="apache2" state="started" enabled="true"   

  - name: installer MySQL DB server
    apt:
      name: mysql-server
      state: latest  

  - name: avoir php7 installé
    apt: 
      name: php7.0-cli
      state: latest

  
   
